# Generated by Django 3.2.5 on 2021-09-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20210923_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-shared_on']},
        ),
    ]
